spring:
  application:
    name: demo-stock
dubbo:
  scan:
    base-packages: cn.zewade.stock.dubbo
  registry:
    address: localhost:2181
    protocol: zookeeper
    timeout: 60000
  application:
    qos-port: 22221
  protocol:
    port: 20881
server:
  port: 9081