spring:
  application:
    name: demo-account
dubbo:
  scan:
    base-packages: cn.zewade.account.dubbo
  registry:
    address: localhost:2181
    protocol: zookeeper
    timeout: 60000
  application:
    qos-port: 22220
  protocol:
    port: 20880
server:
  port: 9080